### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by xxhhccisme** [techblue/jmagick#15]
I have been using jmagick for a while, it seems like there is a little bit memory leak, but i destroy every single image i create, i wonder if this problem happened to any of you, and how you solved it.

This is my gc log.
![image](https://cloud.githubusercontent.com/assets/7658444/12547711/dd36a8ac-c38c-11e5-8d2d-47ba67e49ef6.png)

hope someone can help, thxs in advance.

**Comment by ferbar** [comment]
found many memory leaks. see:
https://github.com/techblue/jmagick/commit/c25399926eb3b6763ce7d61d029fd4ff92e5c257

@techblue: you might want to merge that ;-)

**Comment by ajkerr** [comment]
@ferbar Would you mind submitting a pull request with that commit?

**Comment by ferbar** [comment]
@techblue: may I ask you to close/rejected this pull request. Looks as if I can not create a new pull request as long as this one is open:

> want to use 64 bit dll
> #11 opened on 20 Sep 2015 by bhangalep

thx!

**Comment by xxhhccisme** [comment]
This problem kills me, cause we use it in production, the program will oom after a week or two. @ferbar Can i use it in production after merge this pull request ?

**Comment by ferbar** [comment]
give it a try ... I just checked the functions I am using for memory leaks, so expect to be more...

why not restarting your service once a day? There are also memory leaks in imagemagick, especially when things go wrong.

**Comment by ajkerr** [comment]
@ferbar I closed the #11, although I have no idea why that would prevent you from creating a new PR. Please ensure that your PR only includes the commit related to the memory leaks.

**Comment by ferbar** [comment]
Took some time but ... done ...

**Comment by ajkerr** [comment]
Sorry for the delay - your PR has been merged. Hopefully this fixes the memory leaks.
