### ISSUE TITLE
Facing issue with configure

### ISSUE THREAD

**Issue by jaiswalakshay** [techblue/jmagick#31]
**to configure JMagick I used following command:**
$./configure --prefix=/usr/local/ -with-java-home=/usr/java/jdk1.8.0_25/ --with-magick-home=/usr/local/include/ImageMagick-7/ --enable-shared

**Error Messages:**
No package 'MagickCore' found
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing`MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
checking magick/api.h usability... no
checking magick/api.h presence... no
checking for magick/api.h... no
configure: error: 'Unable to find ImageMagick header files'

**Comment by jhorowitz-firedrum** [comment]
@jaiswalakshay, this should now work since ImageMagick 7 support has been integrated into master.

If you are still around and interested, please try again and let us know if this issue is still valid.

Thanks you!
