### ISSUE TITLE
Issues while using with ImageMagick 7

### ISSUE THREAD

**Issue by mghwang** [techblue/jmagick#47]
I'm using jmagick in one of my development projects, and recently I faced some problems with the master branch of jmagick + ImageMagick 7.

The first problem is about getPixelPacket() function which is used in DrawInfo.setFill(PixelPacket) method. 
And the second problem is about MagickImage.transformImage() method.

Both problems occur only in >= ImageMagick 7 environment.
Fortunately, I could fix them and made a pull request (#46 ). Please check it.

**Comment by nordfalk** [comment]
Looks good to me - merging.
Thanks for your contribution!
