### ISSUE TITLE
jmagick incompatability with Tomcat8

### ISSUE THREAD

**Issue by sgoble-vp** [techblue/jmagick#49]
When trying to use jmagick commands in a Tomcat8 app we would keep on getting "NoClassDefFoundError" errors. I singled it out to this line in the Magick.java class: 

`ClassLoader.getSystemClassLoader()
                        .loadClass("magick.MagickLoader").newInstance();`

It is my basic understanding that Tomcat does not store app level classes in the system loader and so this line was failing to find the class. I changed the line to the following which solved the issue:

`Magick.class.getClassLoader()
                        .loadClass("magick.MagickLoader").newInstance();`

**Comment by nordfalk** [comment]
Fixed in https://github.com/techblue/jmagick/commit/c1cdad3b18b5394c83e6376fb90cb65aec78949c
