### ISSUE TITLE
configure: error: 'Unable to find ImageMagick header files'

### ISSUE THREAD

**Issue by moagarwa** [techblue/jmagick#51]
I am not able to find api.h while configuring jMAgick

**Comment by a-schild** [comment]
What platform are you trying to build?
The api.h is provided comming from the imagemagick package, so perhaps you have to specify where they are located for the build

**Comment by moagarwa** [comment]
I am on Mac 10.14.5.

However I have resolved the issue by directly using imagmagick from command line.
Thanks for your help.

**Comment by a-schild** [comment]
Could you please close the issue in that case

**Comment by moagarwa** [comment]
Closed issue
