### ISSUE TITLE
NoiseType.java types not consistent in magick_MagickImage.c

### ISSUE THREAD

**Issue by MolotovCherry** [techblue/jmagick#54]
The java `noiseType`'s are not consistent with implementation of the `noiseType`'s in `addNoiseImage` in `magick_MagickImage.c`. Also take note that the numbers are off by one as well. Perhaps this has to do with recent IM7 changes?

`magick_MagickImage.c`
```
    switch (noiseType) {
        default: noiseEnum = UniformNoise;                break;
        case 1:  noiseEnum = GaussianNoise;               break;
        case 2:  noiseEnum = MultiplicativeGaussianNoise; break;
        case 3:  noiseEnum = ImpulseNoise;                break;
        case 4:  noiseEnum = LaplacianNoise;              break;
        case 5:  noiseEnum = PoissonNoise;                break;
    }
```

`NoiseType.java`
```
    public final static int UndefinedNoise = 0;
    public final static int UniformNoise = 1;
    public final static int GaussianNoise = 2;
    public final static int MultiplicativeGaussianNoise = 3;
    public final static int ImpulseNoise = 4;
    public final static int LaplacianNoise = 5;
    public final static int PoissonNoise = 6;
    public final static int RandomNoise = 7;
```

**Comment by cherryleafroad** [comment]
Imagemagick6 Noise Types are the same as Imagemagick 7 Noise Types, also the same as in the Java, but not the same as is listed in the C file (which also lists the incorrect types as well, thereby causing wrong results).

The C code should be able to be safely changed to match the Java to fix it.

**Comment by nordfalk** [comment]
Dear @cherryleafroad if you manage to do a pull request then I'd be happy to review the changes and merge it.
