### ISSUE TITLE
IM7 Java_magick_MagickImage_colorizeImage causing segfault

### ISSUE THREAD

**Issue by cherryleafroad** [techblue/jmagick#56]
I'm using IM7 `7.0.8-3`, and this code here is causing a segfault for me.

`magick_MagickImage.c`
`Java_magick_MagickImage_colorizeImage @ 970`
```
#if MagickLibVersion < 0x700
    if (!getPixelPacket(env, target, &pixel)) {
#else
    if (!getPixelPacket(env, target, pixel)) {
#endif
	throwMagickException(env, "Unable to get pixel values");
	return NULL;
    }
```

After removing it and recompiling, everything works properly

**Comment by cherryleafroad** [comment]
Here's how to fix the bug:

`Java_magick_MagickImage_colorizeImage`

Change 
```
#if MagickLibVersion < 0x700
    PixelPacket pixel;
#else
    PixelInfo *pixel;
#endif
```
TO
```
#if MagickLibVersion < 0x700
    PixelPacket pixel;
#else
    PixelInfo pixel;
#endif
```

Change
```
#if MagickLibVersion < 0x700
    if (!getPixelPacket(env, target, &pixel)) {
#else
    if (!getPixelPacket(env, target, pixel)) {
#endif
```
TO
```
if (!getPixelPacket(env, target, &pixel)) {
```

Change
```    newImage = ColorizeImage(image, cstrOpacity, pixel, exception);```
TO
```    newImage = ColorizeImage(image, cstrOpacity, &pixel, exception);```

This fixes the problem

**Comment by cherryleafroad** [comment]
I created a pull request to fix this issue

**Comment by nordfalk** [comment]
Looks good to me. Ive accepted the PR. Thank you for the fix!
