### ISSUE TITLE
Gif file size problem

### ISSUE THREAD

**Issue by bayarmunkh** [techblue/jmagick#6]
I'm having an issue with reading gif files. Does anyone know why the following expression isn't true?

```scala
      val filename = "giphy.gif"
      val bytes = Source.fromFile(filename)(Codec.ISO8859).map(_.toByte).toArray

      val info = new ImageInfo(filename)
      val image = new MagickImage(info)
      val magicBytes = image.imageToBlob(info)

      bytes.size == magicBytes.size //'15301' is not equal to '11329'
```

**Comment by ajkerr** [comment]
Hard to tell without knowing which libraries you're using to read the file in the first two lines.

**Comment by bayarmunkh** [comment]
it's written in Scala, just a wrapper around java FileInputStream and InputStream.

Here is the full source code. https://github.com/scala/scala/blob/v2.11.5/src/library/scala/io/Source.scala#L13

**Comment by ajkerr** [comment]
Hmm, ok, you may be better off asking over on the jmagick mailing list (still hosted on SourceForge).

**Comment by bayarmunkh** [comment]
looks like it's reading only the first frame of an animated gif. Is this a known issue?

**Comment by ajkerr** [comment]
I'm guessing here, but it's possible that the C API you're after is actually http://www.imagemagick.org/api/blob.php#ImagesToBlob 

If so, you'd need to add a new method to jmagick to support this C API.
