### ISSUE TITLE
Jmagick has issues scaling image when it is too white - "failed - magick.MagickException: Pixels size too small"

### ISSUE THREAD

**Issue by ysgm1811** [techblue/jmagick#63]
If the image is too while then scaling is failing with the following exception 

"failed - magick.MagickException: Pixels size too small". But if I resize directly with the imagemagick command-line tool, it works.

**Comment by nordfalk** [comment]
Could you provide some sample code?
And... please write when/if you have resolvet the issue ;-)

**Comment by nordfalk** [comment]
missing reply - closing
