### ISSUE TITLE
Is there any java 11 or 17 support ?

### ISSUE THREAD

**Issue by hangingman** [techblue/jmagick#65]
Hi, I recently try to build jmagick with java17. But I got following error message.

```
checking for javah... not_found
configure: error: 'No Java header generator (javah) found'
```

Because, javah command was superseded  by "javac -h" in jdk10.
Is there any plan to support java 11 or higher ?
If we had propose pull request to support that, it's useful ?

**Comment by nordfalk** [comment]
Hi there, make a PR and ping me to get  it merged. Thanks :-)

**Comment by nordfalk** [comment]
Fixed in https://github.com/techblue/jmagick/pull/66
