### ISSUE TITLE
please tag or release

### ISSUE THREAD

**Issue by bastien-roucaries** [techblue/jmagick#72]
Hi

Can you tag or make release ?

Thanks

**Comment by bastien-roucaries** [comment]
A 6.7.8~alpha tag will really help debian project

**Comment by nordfalk** [comment]
Sure, is this fine? https://github.com/techblue/jmagick/releases/tag/6.7.8

**Comment by nordfalk** [comment]
Or, shouldnt it be 7.1.1-10, to follow ImageMagick? 
 https://github.com/techblue/jmagick/blob/b4412afd5303aa6aa389b66ccea4bef2eabf0aca/.github/workflows/jmagick_build.yml#L23

**Comment by bastien-roucaries** [comment]
Le vendredi 30 août 2024, 13:59:49 UTC Jacob Nordfalk a écrit :
> Or, shouldnt it be 7.1.1-10, to follow ImageMagick? 
>  https://github.com/techblue/jmagick/blob/b4412afd5303aa6aa389b66ccea4bef2eabf0aca/.github/workflows/jmagick_build.yml#L23
> 
> 
No the previous tag is nice
