### ISSUE TITLE
64-bit jmagick.dll

### ISSUE THREAD

**Issue by RevanProdigalKnight** [techblue/jmagick#9]
It's currently impossible to run jmagick on a 64-bit JVM because it can't load a 32-bit DLL on a 64-bit JVM. Are there any plans to change this?

The stack trace I get:

    C:\Program Files (x86)\ImageMagick-6.3.9-Q8\jmagick.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
    java.lang.UnsatisfiedLinkError
      at java.lang.ClassLoader$NativeLibrary.load(Native Method)
      at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
      at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
      at java.lang.Runtime.loadLibrary0(Runtime.java:870)
      at java.lang.System.loadLibrary(System.java:1119)
      at magick.MagickLoader.<clinit>(MagickLoader.java:13)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
      at java.lang.Class.newInstance(Class.java:438)
      at magick.Magick.<clinit>(Magick.java:21)
      ...

**Comment by ajkerr** [comment]
Where are you getting the jmagick.dll from?

**Comment by RevanProdigalKnight** [comment]
I'm getting it from the jmagick-win-6.3.9-Q8.zip file [here](http://www.jmagick.org/6.3.9/)

**Comment by ajkerr** [comment]
Those binaries are quite old - in fact, I'm not even sure who maintains the www.jmagick.org website.  You would probably be better off building from source from the latest github master branch.

**Comment by ferbar** [comment]
I found it rather complicated to get a fresh dll. This is what I found lurking around: 
https://github.com/ferbar/jmagick/tree/master/bin

Be aware that you need the corresponding imagemagick.dll (version 6.8.9-Q16 or 6.4.0 )

**Comment by viktara** [comment]
I am hosting the jmagick.org domain, it's been a long time since we build any binaries.

If I can find some time I could set up CI to produce some binaries - let me know if anyone thinks it worthwhile?

**Comment by ajkerr** [comment]
@viktara That might be useful, especially for Windows.

The current JMagick code base isn't guaranteed to work properly against anything higher than ImageMagick 6.7.7 right now (which, not coincidentally, is the version shipped with Ubuntu 14.04 LTS).  This is because ImageMagick has historically been bad about changing the values of constants in their .h files, although they seem to do this much less frequently in recent hears.

**Comment by ajkerr** [comment]
@RevanProdigalKnight There are some new binaries on a pull request that hasn't been merged yet.  You may wish to give them a try.  https://github.com/ferbar/jmagick/commit/43a76526b80b779a6155944dd1f54fa0ab486664

**Comment by RevanProdigalKnight** [comment]
@ajkerr Well, I gave it a try, and now it loads properly, but it's complaining about not being able to find a procedure (which, according to [StackOverflow](http://stackoverflow.com/a/180587/2517631) could be in @ferbar's build or any of the dependencies of that.

I think until a proper CI is set up I should probably try to find an alternative.

**Comment by saraivamarco** [comment]
@viktara It would be useful yes, especially for a 64 bit JVM. I am facing the same issue as @RevanProdigalKnight and 32-bit won't do the trick.
Thanks for your availability to solve this issue.

**Comment by AymanArif** [comment]
I would like to know how this was resolved. I a using 64 bit JVM.
